name: joemoda.com
favicon: null
layout_spectrum: 0.32016
typography_spectrum: 0.53386
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#242831'
    - '#7d705d'
    - '#ad918d'
    - '#ffffff'
    - '#b8cbd9'
  brandStrength: 0.625
  lightness: 0.8125
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose:
  - name: null
    item: null
    url: null
