name: joemoda.com
favicon: null
layout_spectrum: 0.99366
typography_spectrum: 0.53386
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040203'
    - '#fe4316'
    - '#cd9480'
    - '#7a5344'
    - '#d6e13d'
  brandStrength: 0.5625
  lightness: 0.625
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose:
  - name: null
    item: null
    url: null
