name: joemoda.com
favicon: null
layout_spectrum: 0.72087
typography_spectrum: 0.51213
title: Joemoda.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#424a57'
    - '#ffffff'
    - '#020003'
    - '#bcb4b1'
    - '#ffeb00'
  brandStrength: 0.5674915147850104
  lightness: 0.625
  saturation: 0.6536140425187706
  rhythmicContrast: 0.8713870181390584
purpose:
  - name: null
    item: null
    url: null
