name: joemoda.com
favicon: null
layout_spectrum: 0.26463
typography_spectrum: 0.15365
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#424a57'
    - '#ffffff'
    - '#020003'
    - '#bcb4b1'
    - '#ffeb00'
  brandStrength: 0.5625
  lightness: 0.5
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose:
  - name: null
    item: null
    url: null
