name: joemoda.com
favicon: null
logo: null
layout_spectrum: 0.5211517312216324
typography_spectrum: 0.35677034494208887
cta: {}
analytics: {}
opengraph:
  type: ''
  appId: ''
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/b793061c-f40a-4483-99c6-c70af3d53d92.png
color:
  brandColors:
    - '#000000'
    - '#404040'
    - '#808080'
    - '#BFBFBF'
    - '#FFFFFF'
  brandStrength: 0.8631899820072668
  lightness: 0.020006629331590663
  saturation: 0.8301192893556291
  rhythmicContrast: 0.30510716561163487
purpose:
  - type: contact
    label: 'Contact '
    url: 'mailto:ggmoda@gmail.com'
  - type: contact
    label: '+393274249555'
    url: 'tel:+393274249555'
title: International Creative Professional for Hire
description: ''
author:
  name: Joe Moda
  url: www.joemoda.com
  email: ggmoda@gmail.com
content_rating:
  adult: false
navigation:
  - name: 'My first song write, to full production.'
    url: 'https://www.youtube.com/watch?v=klgs6aXFx0E'
    type: external
  - name: Modamouth on Facebook
    url: 'https://www.facebook.com/modamouth/?ref=aymt_homepage_panel'
    type: external
  - name: 'IMDB '
    url: 'http://www.imdb.com/name/nm7479108/?ref_=rvi_nm'
    type: external
  - name: 'Giardini Da Incubo '
    url: 'https://vimeo.com/208920725'
    type: external
  - name: Bear Grylls and me - Breaking Point
    url: 'https://vimeo.com/230310372'
    type: external
content: []
github: true
