name: joemoda.com
favicon: null
layout_spectrum: 0.32016
typography_spectrum: 0.53386
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fafbf6'
    - '#c1c2bd'
    - '#160000'
    - '#9d0000'
    - '#5a3219'
  brandStrength: 0.1875
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.75
purpose:
  - name: null
    item: null
    url: null
